version: "3"
services:
  client:
  container_name: client
  build:
    context: .
    dockerfile: DockerfileClient
  image: mooonyechan97/react-map
  ports:
    - "80:3000"
server:
  container_name: server
  build:
    context: .
    dockerfile: DockerfileServer
  image: moonyechan97/express-server
  ports:
    - "4000:4000"